#!/bin/sh

# usage:
#   run_test <commands_prefix> <training_set> <testing_set> <model> <output> <progress_message> <expected>

: ${DIFF_CMD:=diff -u}

set -e

opts=''
while printf '%s\n' "$1" | grep -q '^-'; do
    opts="$opts $1"
    shift
done

test $# -eq 7

train_cmd="$1-train"
predict_cmd=`echo $1-predict | sed 's/scikit_[^-]*/scikit/'`
training_set="$2"
testing_set="$3"
model="$4"
output="$5"
message="$6"
expected="$7"

echo "$message" 1>&2

"$train_cmd" $opts $TRAIN_CMD_OPTS "$training_set" "$model"
"$predict_cmd" $PREDICT_CMD_OPTS "$testing_set" "$model" "$output"
awk '{print $1}' "$output" > "$output.tmp"
mv "$output.tmp" "$output"
if test -n "$expected"; then
    $DIFF_CMD "$expected" "$output"
fi
