#!/usr/bin/env python

import pickle
import sys

from svmlight_loader import load_svmlight_file
from sklearn import svm

with open(sys.argv [2], 'rb') as f:
    clf = pickle.load(f)
    n_features = pickle.load(f)

    X_test, y_test = load_svmlight_file(sys.argv [1], n_features)

result = clf.predict(X_test)

with open(sys.argv [3], 'w') as output:
    for i in range(0, len(result)):
        output.write('%d' % (result [i]) + "\n")
