#!/usr/bin/env python

import pickle
import sys

from svmlight_loader import load_svmlight_file
from sklearn import svm

X_train, y_train = load_svmlight_file(sys.argv [1])
clf = svm.LinearSVC()
clf.fit_transform(X_train, y_train)
with open(sys.argv [2], 'wb') as f:
    pickle.dump(clf, f)
    pickle.dump(X_train.shape[1], f)
