#!/bin/sh

# Copyright (c) 2016 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

: ${CLASSIAS_TRAIN:=classias-train}
: ${GZIP_CMD:=gzip}
: ${TMPDIR:=/tmp}

set -e
export LC_ALL=C

usage (){
    cat 1>&2 <<EOF
class-train - wrapper over classias-train(1)
usage: class-train [OPTIONS] -- [CL_OPTIONS] training_set_file model_file
OPTIONS:
    -h     display this screen
    -Z     read gzipped training set from <training_set_file>.gz
CL_OPTIONS:
    See $CLASSIAS_TRAIN options for details
EOF
}

sig_handler (){
    on_exit
    trap - "$1"
    kill -"$1" $$
}

on_exit(){
    rm -rf "$tmp_dir"
}

trap "sig_handler INT"  INT
trap "on_exit" 0

compressed=
while getopts hZ f; do
    case "$f" in
	'?')
	    usage
	    exit 1;;
	h)
	    usage
	    exit 0;;
	Z)
	    compressed=1;;
    esac
done
shift `expr $OPTIND - 1`

if test $# -lt 2; then
    usage
    exit 1
fi

tmp_dir=`mktemp -d "$TMPDIR"/class-train.XXXXXX`
fifo_name="$tmp_dir/fifo"

split_args (){
    while test $# -ne 2; do
	printf '%s ' "$1"
	shift
    done
    printf '\n'
    printf '%s\n' "$1"
    printf '%s\n' "$2"
}

split_args "$@" | {
    read args
    read training_set
    read model

    if test -n "$compressed"; then
	mkfifo "$fifo_name"
	$GZIP_CMD -dc "$training_set.gz" > "$fifo_name" &
	training_set="$fifo_name"
    fi

    $CLASSIAS_TRAIN -m "$model" "$training_set" $args
    wait
}
