#!/bin/sh

# Copyright (c) 2016-2018 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

: ${CLASSIAS_TAG:=classias-tag}
: ${GZIP_CMD:=gzip}
: ${TMPDIR:=/tmp}

set -e
export LC_ALL=C

usage (){
    cat 1>&2 <<EOF
class-predict - wrapper over classias-tag(1)
usage: class-train [OPTIONS] -- [CL_OPTIONS] testing_set_file model_file output_file
OPTIONS:
    -h         display this screen
    -Z         read gzipped training set from <training_set_file>.gz
    -b num     1 -- probability score, 0 -- raw score.
               Empty string (the default) -- no score on output.
CL_OPTIONS:
    See $CLASSIAS_TAG options for details
EOF
}

sig_handler (){
    on_exit
    trap - "$1"
    kill -"$1" $$
}

on_exit(){
    rm -rf "$tmp_dir"
}

trap "sig_handler INT"  INT
trap "on_exit" 0

compressed=
score=1
while getopts b:hZ f; do
    case "$f" in
	'?')
	    usage
	    exit 1;;
	h)
	    usage
	    exit 0;;
	Z)
	    compressed=1;;
	b)
	    score=$OPTARG;;
    esac
done
shift `expr $OPTIND - 1`

if test $# -lt 3; then
    usage
    exit 1
fi

split_args (){
    while test $# -ne 3; do
	printf '%s ' "$1"
	shift
    done
    printf '\n'
    printf '%s\n' "$1"
    printf '%s\n' "$2"
    printf '%s\n' "$3"
}

convert () {
    awk -F':' '
$0 == "@boi" {
    next
}

$0 == "@eoi" {
    printf "%s %.8g", best, h[best]
    for (k in h) {
        if (k != best)
            printf " %s %.8g", k, h[k]
    }
    printf "\n"
    next
}

{
    if ($1 ~ /^[+]/){
        best = $1+0
    }else{
        $1 = -$1
    }

    h[$1+0] = $2
}
' "$@"
}

split_args "$@" | {
    read args
    read input
    read model
    read output

    if test "$score" = 0; then
	args="$args -wa"
    elif test "$score" = 1; then
	args="$args -pa"
    else
	convert() {
	    cat
	}
    fi

    if test -n "$compressed"; then
	tmp_dir=`mktemp -d "$TMPDIR"/class-predict.XXXXXX`
	fifo_name="$tmp_dir/fifo"

	mkfifo "$fifo_name"
	$GZIP_CMD -dc "$input.gz" > "$fifo_name" &
	input="$fifo_name"
    fi

    eval "classias-tag -m $model $args < $input" | convert > $output
}
