#!/bin/sh

usage (){
    cat 1>&2 <<EOF
class-train - wrapper over classias-train(1)

usage: class-train [OPTIONS] training_set_file model_file
OPTIONS are passed directly to classias-train(1)
EOF
}

if test "_-h" = "_$1"; then
    usage
    exit 0
fi

if test $# -lt 2; then
    usage
    exit 1
fi

split_args (){
    while test $# -ne 1; do
	printf '%s ' "$1"
	shift
    done
    printf '\n'
    printf '%s\n' "$1"
}

split_args "$@" | {
    read args
    read model
    eval "classias-train -m $model $args"
}
