#!/bin/sh

# Copyright (c) 2016-2018 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

: ${VW:=vw}
: ${GZIP_CMD:=gzip}
: ${TMPDIR:=/tmp}

set -e
export LC_ALL=C

usage (){
    cat 1>&2 <<EOF
vw-predict - wrapper over vm(1) for predicting

usage: vw-predict [OPTIONS] -- [VW_OPTIONS] testing_set_file model_file output_file
OPTIONS:
    -h     display this screen
    -Z     read gzipped testing set from <testing_set_file>.gz
VW_OPTIONS:
    See $VW options for details
EOF
}

sig_handler (){
    on_exit
    trap - "$1"
    kill -"$1" $$
}

on_exit(){
    rm -rf "$tmp_dir"
}

trap "sig_handler INT"  INT
trap "on_exit" 0

compressed=
while getopts hZ f; do
    case "$f" in
	'?')
	    usage
	    exit 1;;
	h)
	    usage
	    exit 0;;
	Z)
	    compressed=1;;
    esac
done
shift `expr $OPTIND - 1`

if test $# -lt 3; then
    usage
    exit 1
fi

tmp_dir=`mktemp -d "$TMPDIR"/vw-predict.XXXXXX`
fifo_name="$tmp_dir/fifo"
fifo2_name="$tmp_dir/fifo2"

split_args (){
    while test $# -ne 3; do
	printf '%s ' "$1"
	shift
    done
    printf '\n'
    printf '%s\n' "$1"
    printf '%s\n' "$2"
    printf '%s\n' "$3"
}

split_args "$@" | {
    read args
    read input
    read model
    read output

    if test -n "$compressed"; then
	mkfifo "$fifo_name"
	$GZIP_CMD -dc "$input.gz" > "$fifo_name" &
	input="$fifo_name"
    fi

    mkfifo "$fifo2_name"
    awk '{tag=$1; $1 = ""; print tag, "|" $0}' "$input" > "$fifo2_name" &
    
    eval "$VW --quiet $args -t $fifo2_name -i $model -p /dev/stdout" |
	awk '{print int($1)}' > "$output"
    wait
}
