#!/bin/sh

# Copyright (c) 2016 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

usage (){
    cat 1>&2 <<EOF
vw-train - wrapper over vw(1)

usage: vw-train [OPTIONS] training_set_file model_file
OPTIONS are passed directly to vw(1)
EOF
}

if test "_-h" = "_$1"; then
    usage
    exit 0
fi

if test $# -lt 2; then
    usage
    exit 1
fi

split_args (){
    while test $# -ne 2; do
	printf '%s ' "$1"
	shift
    done
    printf '\n'
    printf '%s\n' "$1"
    printf '%s\n' "$2"
}

split_args "$@" | {
    read args
    read training_set
    read model

    tmpin="$training_set.vwtmp"
    awk '{tag=$1; $1 = ""; print tag, "|" $0}' "$training_set" > "$tmpin"

    eval "vw $tmpin --quiet -f $model $args"
}
