#!/usr/bin/env python3

# Copyright (c) 2016-2019 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import pickle
import sys
import os

from sklearn.exceptions import ConvergenceWarning
from sklearn.datasets import load_svmlight_file
from sklearn import svm

X_train, y_train = load_svmlight_file(sys.argv [1])
#feature_count = os.getenv("HERISVM_FC")
#sys.stderr.write("feature_count=" + str(feature_count) + "\n")
#sys.stderr.write("train set feature_count=" + str(X_train.shape[1]) + "\n")
#if feature_count != None:
#    feature_count = int(feature_count)
#else:
#    feature_count = X_train.shape[1]

kwargs_constructor = {}
kwargs_fit = {}

clf = svm.LinearSVC(**kwargs_constructor)
clf.fit(X_train, y_train, **kwargs_fit)

with open(sys.argv [2], 'wb') as f:
    pickle.dump(clf, f)
#    pickle.dump(feature_count, f)
    pickle.dump(X_train.shape[1], f)
